### ISSUE TITLE
Incomplete installation: lib doesn't seem to get installed

### ISSUE THREAD

**Issue by kassi** [davla/yeoman-python-poetry-vscode#1]
I tried a new installation in a fresh environment using asdf: node 18.16.0, python 3.11.3.
```
  npm i -g yo generator-python-poetry-vscode
```
succeeds.
Then
```
% yo python-poetry-vscode
Error python-poetry-vscode

Cannot find module '/Users/me/.asdf/installs/nodejs/18.16.0/.npm/lib/node_modules/generator-python-poetry-vscode/lib/base-generator.js' imported from /Users/me/.asdf/installs/nodejs/18.16.0/.npm/lib/node_modules/generator-python-poetry-vscode/generators/app/index.js
```
and a
```
% ls -l1 /Users/me/.asdf/installs/nodejs/18.16.0/.npm/lib/node_modules/generator-python-poetry-vscode
LICENSE
README.md
generators/
node_modules/
package.json
```
There's no `lib`.

**Comment by davla** [comment]
Sorry for the late reply, and thank you for the report.

I'm quite sure this can be solved by including `lib` in the `files` section in `package.json`, but I'll have to find a way to verify first.

**Comment by davla** [comment]
And that seems to have done the trick. Version [1.1.1](https://www.npmjs.com/package/generator-python-poetry-vscode/v/1.1.1) is out.

I won't close this until I write a ci check for packaging though.
